### ISSUE TITLE
Help in supporting ppcle64 arch binary

### ISSUE THREAD

**Issue by Jainbrt** [lework/skopeo-binary#7]
Hi @lework , 

First of all, thanks for hosting skopeo binary as single source on the internet to get and use as it is. 

We were playing with kuberspray, where k8s installation was failing [due to not finding skopeo binary for ppcle64 arch ](https://github.com/kubernetes-sigs/kubespray/issues/11038). 

Would it be possible to support the same arch for broader use of skopeo binary ? Also we would be happy to help if required. 

Thanks in advance.
Abhishek

**Comment by lework** [comment]
@Jainbrt 
New version has been added ppcle64, https://github.com/lework/skopeo-binary/releases/tag/v1.15.0

**Comment by Jainbrt** [comment]
Awesome.
