### ISSUE TITLE
Incompatible Go version causing build failure on GitHub Actions

### ISSUE THREAD

**Issue by LinkeDmitry** [lework/skopeo-binary#8]
During the build process on GitHub Actions, the workflow is encountering an error due to an incompatible Go version specified in the `go.mod` file and the one used in the Docker image. The current Docker image (`golang:1.20-alpine3.16`) does not support Go version `1.21.0` specified in `go.mod`, leading to the following error:
```
/build/go.mod:4: invalid go version '1.21.0': must match format 1.23
```

@lework , Please update `Go` version in `build.yml` to 1.21 or higher to resolve this issue.

**Comment by lework** [comment]
Thanks, it's fixed.
